/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogSection { 'title' : string, 'content' : string }
export interface ContentDraft {
  'id' : bigint,
  'metaDescription' : string,
  'created' : Timestamp,
  'topic' : string,
  'seoTags' : Array<string>,
  'author' : Principal,
  'keywords' : Array<string>,
  'versionHistory' : Array<ContentDraftVersion>,
  'updated' : Timestamp,
  'sections' : Array<BlogSection>,
  'mainImage' : [] | [ExternalBlob],
}
export interface ContentDraftVersion {
  'created' : Timestamp,
  'content' : ContentDraft,
  'versionNumber' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface KeywordMetric {
  'clicks' : bigint,
  'period' : string,
  'impressions' : bigint,
  'timestamp' : Timestamp,
  'avgPosition' : bigint,
}
export type ListingStatus = { 'notStarted' : null } |
  { 'submitted' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface PlatformCatalogEntry {
  'id' : bigint,
  'region' : string,
  'created' : Timestamp,
  'country' : string,
  'estimatedTraffic' : SeoImpactRange,
  'submissionGuide' : string,
  'name' : string,
  'description' : string,
  'updated' : Timestamp,
  'category' : PlatformCategory,
  'estimatedSeoImpact' : SeoImpactRange,
  'requirements' : string,
}
export type PlatformCategory = { 'forum' : null } |
  { 'directory' : null } |
  { 'news' : null } |
  { 'reviewSite' : null } |
  { 'contentSharing' : null } |
  { 'socialMedia' : null };
export interface SeoImpactRange { 'max' : bigint, 'min' : bigint }
export interface SubmissionPlan {
  'status' : ListingStatus,
  'created' : Timestamp,
  'userId' : Principal,
  'updated' : Timestamp,
  'notes' : string,
  'platformId' : bigint,
  'submissionDate' : [] | [Timestamp],
  'submissionUrl' : [] | [string],
}
export type Timestamp = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'organization' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContentDraftVersion' : ActorMethod<
    [bigint, ContentDraftVersion],
    undefined
  >,
  'addKeywordMetric' : ActorMethod<[string, KeywordMetric], undefined>,
  'addPlatformCatalogEntry' : ActorMethod<[PlatformCatalogEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateSubmissionPlan' : ActorMethod<[SubmissionPlan], undefined>,
  'generateOrUpdateContentDraft' : ActorMethod<[ContentDraft], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKeywordMetrics' : ActorMethod<[string, string], Array<KeywordMetric>>,
  'getSubmissionPlans' : ActorMethod<[Principal], Array<SubmissionPlan>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCatalogEntries' : ActorMethod<
    [[] | [PlatformCategory], [] | [string]],
    Array<PlatformCatalogEntry>
  >,
  'updatePlatformCatalogEntry' : ActorMethod<
    [bigint, PlatformCatalogEntry],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];