/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContentDraftVersion = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const BlogSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ContentDraft = IDL.Record({
  'id' : IDL.Nat,
  'metaDescription' : IDL.Text,
  'created' : Timestamp,
  'topic' : IDL.Text,
  'seoTags' : IDL.Vec(IDL.Text),
  'author' : IDL.Principal,
  'keywords' : IDL.Vec(IDL.Text),
  'versionHistory' : IDL.Vec(ContentDraftVersion),
  'updated' : Timestamp,
  'sections' : IDL.Vec(BlogSection),
  'mainImage' : IDL.Opt(ExternalBlob),
});
ContentDraftVersion.fill(
  IDL.Record({
    'created' : Timestamp,
    'content' : ContentDraft,
    'versionNumber' : IDL.Nat,
  })
);
export const KeywordMetric = IDL.Record({
  'clicks' : IDL.Nat,
  'period' : IDL.Text,
  'impressions' : IDL.Nat,
  'timestamp' : Timestamp,
  'avgPosition' : IDL.Nat,
});
export const SeoImpactRange = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
export const PlatformCategory = IDL.Variant({
  'forum' : IDL.Null,
  'directory' : IDL.Null,
  'news' : IDL.Null,
  'reviewSite' : IDL.Null,
  'contentSharing' : IDL.Null,
  'socialMedia' : IDL.Null,
});
export const PlatformCatalogEntry = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'created' : Timestamp,
  'country' : IDL.Text,
  'estimatedTraffic' : SeoImpactRange,
  'submissionGuide' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'updated' : Timestamp,
  'category' : PlatformCategory,
  'estimatedSeoImpact' : SeoImpactRange,
  'requirements' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListingStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'submitted' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SubmissionPlan = IDL.Record({
  'status' : ListingStatus,
  'created' : Timestamp,
  'userId' : IDL.Principal,
  'updated' : Timestamp,
  'notes' : IDL.Text,
  'platformId' : IDL.Nat,
  'submissionDate' : IDL.Opt(Timestamp),
  'submissionUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'organization' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContentDraftVersion' : IDL.Func([IDL.Nat, ContentDraftVersion], [], []),
  'addKeywordMetric' : IDL.Func([IDL.Text, KeywordMetric], [], []),
  'addPlatformCatalogEntry' : IDL.Func([PlatformCatalogEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateSubmissionPlan' : IDL.Func([SubmissionPlan], [], []),
  'generateOrUpdateContentDraft' : IDL.Func([ContentDraft], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKeywordMetrics' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(KeywordMetric)],
      ['query'],
    ),
  'getSubmissionPlans' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SubmissionPlan)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCatalogEntries' : IDL.Func(
      [IDL.Opt(PlatformCategory), IDL.Opt(IDL.Text)],
      [IDL.Vec(PlatformCatalogEntry)],
      ['query'],
    ),
  'updatePlatformCatalogEntry' : IDL.Func(
      [IDL.Nat, PlatformCatalogEntry],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContentDraftVersion = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const BlogSection = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ContentDraft = IDL.Record({
    'id' : IDL.Nat,
    'metaDescription' : IDL.Text,
    'created' : Timestamp,
    'topic' : IDL.Text,
    'seoTags' : IDL.Vec(IDL.Text),
    'author' : IDL.Principal,
    'keywords' : IDL.Vec(IDL.Text),
    'versionHistory' : IDL.Vec(ContentDraftVersion),
    'updated' : Timestamp,
    'sections' : IDL.Vec(BlogSection),
    'mainImage' : IDL.Opt(ExternalBlob),
  });
  ContentDraftVersion.fill(
    IDL.Record({
      'created' : Timestamp,
      'content' : ContentDraft,
      'versionNumber' : IDL.Nat,
    })
  );
  const KeywordMetric = IDL.Record({
    'clicks' : IDL.Nat,
    'period' : IDL.Text,
    'impressions' : IDL.Nat,
    'timestamp' : Timestamp,
    'avgPosition' : IDL.Nat,
  });
  const SeoImpactRange = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
  const PlatformCategory = IDL.Variant({
    'forum' : IDL.Null,
    'directory' : IDL.Null,
    'news' : IDL.Null,
    'reviewSite' : IDL.Null,
    'contentSharing' : IDL.Null,
    'socialMedia' : IDL.Null,
  });
  const PlatformCatalogEntry = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'created' : Timestamp,
    'country' : IDL.Text,
    'estimatedTraffic' : SeoImpactRange,
    'submissionGuide' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'updated' : Timestamp,
    'category' : PlatformCategory,
    'estimatedSeoImpact' : SeoImpactRange,
    'requirements' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListingStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'submitted' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SubmissionPlan = IDL.Record({
    'status' : ListingStatus,
    'created' : Timestamp,
    'userId' : IDL.Principal,
    'updated' : Timestamp,
    'notes' : IDL.Text,
    'platformId' : IDL.Nat,
    'submissionDate' : IDL.Opt(Timestamp),
    'submissionUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'organization' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContentDraftVersion' : IDL.Func([IDL.Nat, ContentDraftVersion], [], []),
    'addKeywordMetric' : IDL.Func([IDL.Text, KeywordMetric], [], []),
    'addPlatformCatalogEntry' : IDL.Func([PlatformCatalogEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateSubmissionPlan' : IDL.Func([SubmissionPlan], [], []),
    'generateOrUpdateContentDraft' : IDL.Func([ContentDraft], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKeywordMetrics' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(KeywordMetric)],
        ['query'],
      ),
    'getSubmissionPlans' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SubmissionPlan)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCatalogEntries' : IDL.Func(
        [IDL.Opt(PlatformCategory), IDL.Opt(IDL.Text)],
        [IDL.Vec(PlatformCatalogEntry)],
        ['query'],
      ),
    'updatePlatformCatalogEntry' : IDL.Func(
        [IDL.Nat, PlatformCatalogEntry],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };