/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SeoImpactRange {
    max: bigint;
    min: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Timestamp = bigint;
export interface ContentDraft {
    id: bigint;
    metaDescription: string;
    created: Timestamp;
    topic: string;
    seoTags: Array<string>;
    author: Principal;
    keywords: Array<string>;
    versionHistory: Array<ContentDraftVersion>;
    updated: Timestamp;
    sections: Array<BlogSection>;
    mainImage?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BlogSection {
    title: string;
    content: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SubmissionPlan {
    status: ListingStatus;
    created: Timestamp;
    userId: Principal;
    updated: Timestamp;
    notes: string;
    platformId: bigint;
    submissionDate?: Timestamp;
    submissionUrl?: string;
}
export interface PlatformCatalogEntry {
    id: bigint;
    region: string;
    created: Timestamp;
    country: string;
    estimatedTraffic: SeoImpactRange;
    submissionGuide: string;
    name: string;
    description: string;
    updated: Timestamp;
    category: PlatformCategory;
    estimatedSeoImpact: SeoImpactRange;
    requirements: string;
}
export interface ContentDraftVersion {
    created: Timestamp;
    content: ContentDraft;
    versionNumber: bigint;
}
export interface KeywordMetric {
    clicks: bigint;
    period: string;
    impressions: bigint;
    timestamp: Timestamp;
    avgPosition: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    organization?: string;
}
export enum ListingStatus {
    notStarted = "notStarted",
    submitted = "submitted",
    rejected = "rejected",
    accepted = "accepted",
    inProgress = "inProgress"
}
export enum PlatformCategory {
    forum = "forum",
    directory = "directory",
    news = "news",
    reviewSite = "reviewSite",
    contentSharing = "contentSharing",
    socialMedia = "socialMedia"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addContentDraftVersion(draftId: bigint, version: ContentDraftVersion): Promise<void>;
    addKeywordMetric(title: string, metric: KeywordMetric): Promise<void>;
    addPlatformCatalogEntry(entry: PlatformCatalogEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateSubmissionPlan(plan: SubmissionPlan): Promise<void>;
    generateOrUpdateContentDraft(draft: ContentDraft): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getKeywordMetrics(title: string, period: string): Promise<Array<KeywordMetric>>;
    getSubmissionPlans(userId: Principal): Promise<Array<SubmissionPlan>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCatalogEntries(category: PlatformCategory | null, country: string | null): Promise<Array<PlatformCatalogEntry>>;
    updatePlatformCatalogEntry(id: bigint, entry: PlatformCatalogEntry): Promise<void>;
}
import type { BlogSection as _BlogSection, ContentDraft as _ContentDraft, ContentDraftVersion as _ContentDraftVersion, ExternalBlob as _ExternalBlob, ListingStatus as _ListingStatus, PlatformCatalogEntry as _PlatformCatalogEntry, PlatformCategory as _PlatformCategory, SeoImpactRange as _SeoImpactRange, SubmissionPlan as _SubmissionPlan, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addContentDraftVersion(arg0: bigint, arg1: ContentDraftVersion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContentDraftVersion(arg0, await to_candid_ContentDraftVersion_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContentDraftVersion(arg0, await to_candid_ContentDraftVersion_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addKeywordMetric(arg0: string, arg1: KeywordMetric): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addKeywordMetric(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKeywordMetric(arg0, arg1);
            return result;
        }
    }
    async addPlatformCatalogEntry(arg0: PlatformCatalogEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlatformCatalogEntry(to_candid_PlatformCatalogEntry_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlatformCatalogEntry(to_candid_PlatformCatalogEntry_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateSubmissionPlan(arg0: SubmissionPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateSubmissionPlan(to_candid_SubmissionPlan_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateSubmissionPlan(to_candid_SubmissionPlan_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateOrUpdateContentDraft(arg0: ContentDraft): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOrUpdateContentDraft(await to_candid_ContentDraft_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOrUpdateContentDraft(await to_candid_ContentDraft_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKeywordMetrics(arg0: string, arg1: string): Promise<Array<KeywordMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKeywordMetrics(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKeywordMetrics(arg0, arg1);
            return result;
        }
    }
    async getSubmissionPlans(arg0: Principal): Promise<Array<SubmissionPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionPlans(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionPlans(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchCatalogEntries(arg0: PlatformCategory | null, arg1: string | null): Promise<Array<PlatformCatalogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCatalogEntries(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCatalogEntries(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePlatformCatalogEntry(arg0: bigint, arg1: PlatformCatalogEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlatformCatalogEntry(arg0, to_candid_PlatformCatalogEntry_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlatformCatalogEntry(arg0, to_candid_PlatformCatalogEntry_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ListingStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PlatformCatalogEntry_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformCatalogEntry): PlatformCatalogEntry {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PlatformCategory_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformCategory): PlatformCategory {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionPlan_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionPlan): SubmissionPlan {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    organization: [] | [string];
}): {
    name: string;
    email?: string;
    organization?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.email)),
        organization: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.organization))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ListingStatus;
    created: _Timestamp;
    userId: Principal;
    updated: _Timestamp;
    notes: string;
    platformId: bigint;
    submissionDate: [] | [_Timestamp];
    submissionUrl: [] | [string];
}): {
    status: ListingStatus;
    created: Timestamp;
    userId: Principal;
    updated: Timestamp;
    notes: string;
    platformId: bigint;
    submissionDate?: Timestamp;
    submissionUrl?: string;
} {
    return {
        status: from_candid_ListingStatus_n33(_uploadFile, _downloadFile, value.status),
        created: value.created,
        userId: value.userId,
        updated: value.updated,
        notes: value.notes,
        platformId: value.platformId,
        submissionDate: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.submissionDate)),
        submissionUrl: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.submissionUrl))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: string;
    created: _Timestamp;
    country: string;
    estimatedTraffic: _SeoImpactRange;
    submissionGuide: string;
    name: string;
    description: string;
    updated: _Timestamp;
    category: _PlatformCategory;
    estimatedSeoImpact: _SeoImpactRange;
    requirements: string;
}): {
    id: bigint;
    region: string;
    created: Timestamp;
    country: string;
    estimatedTraffic: SeoImpactRange;
    submissionGuide: string;
    name: string;
    description: string;
    updated: Timestamp;
    category: PlatformCategory;
    estimatedSeoImpact: SeoImpactRange;
    requirements: string;
} {
    return {
        id: value.id,
        region: value.region,
        created: value.created,
        country: value.country,
        estimatedTraffic: value.estimatedTraffic,
        submissionGuide: value.submissionGuide,
        name: value.name,
        description: value.description,
        updated: value.updated,
        category: from_candid_PlatformCategory_n43(_uploadFile, _downloadFile, value.category),
        estimatedSeoImpact: value.estimatedSeoImpact,
        requirements: value.requirements
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    submitted: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): ListingStatus {
    return "notStarted" in value ? ListingStatus.notStarted : "submitted" in value ? ListingStatus.submitted : "rejected" in value ? ListingStatus.rejected : "accepted" in value ? ListingStatus.accepted : "inProgress" in value ? ListingStatus.inProgress : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forum: null;
} | {
    directory: null;
} | {
    news: null;
} | {
    reviewSite: null;
} | {
    contentSharing: null;
} | {
    socialMedia: null;
}): PlatformCategory {
    return "forum" in value ? PlatformCategory.forum : "directory" in value ? PlatformCategory.directory : "news" in value ? PlatformCategory.news : "reviewSite" in value ? PlatformCategory.reviewSite : "contentSharing" in value ? PlatformCategory.contentSharing : "socialMedia" in value ? PlatformCategory.socialMedia : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubmissionPlan>): Array<SubmissionPlan> {
    return value.map((x)=>from_candid_SubmissionPlan_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlatformCatalogEntry>): Array<PlatformCatalogEntry> {
    return value.map((x)=>from_candid_PlatformCatalogEntry_n41(_uploadFile, _downloadFile, x));
}
async function to_candid_ContentDraftVersion_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentDraftVersion): Promise<_ContentDraftVersion> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ContentDraft_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentDraft): Promise<_ContentDraft> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_PlatformCatalogEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlatformCatalogEntry): _PlatformCatalogEntry {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PlatformCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlatformCategory): _PlatformCategory {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionPlan_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionPlan): _SubmissionPlan {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlatformCategory | null): [] | [_PlatformCategory] {
    return value === null ? candid_none() : candid_some(to_candid_PlatformCategory_n16(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    metaDescription: string;
    created: Timestamp;
    topic: string;
    seoTags: Array<string>;
    author: Principal;
    keywords: Array<string>;
    versionHistory: Array<ContentDraftVersion>;
    updated: Timestamp;
    sections: Array<BlogSection>;
    mainImage?: ExternalBlob;
}): Promise<{
    id: bigint;
    metaDescription: string;
    created: _Timestamp;
    topic: string;
    seoTags: Array<string>;
    author: Principal;
    keywords: Array<string>;
    versionHistory: Array<_ContentDraftVersion>;
    updated: _Timestamp;
    sections: Array<_BlogSection>;
    mainImage: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        metaDescription: value.metaDescription,
        created: value.created,
        topic: value.topic,
        seoTags: value.seoTags,
        author: value.author,
        keywords: value.keywords,
        versionHistory: await to_candid_vec_n12(_uploadFile, _downloadFile, value.versionHistory),
        updated: value.updated,
        sections: value.sections,
        mainImage: value.mainImage ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.mainImage)) : candid_none()
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: string;
    created: Timestamp;
    country: string;
    estimatedTraffic: SeoImpactRange;
    submissionGuide: string;
    name: string;
    description: string;
    updated: Timestamp;
    category: PlatformCategory;
    estimatedSeoImpact: SeoImpactRange;
    requirements: string;
}): {
    id: bigint;
    region: string;
    created: _Timestamp;
    country: string;
    estimatedTraffic: _SeoImpactRange;
    submissionGuide: string;
    name: string;
    description: string;
    updated: _Timestamp;
    category: _PlatformCategory;
    estimatedSeoImpact: _SeoImpactRange;
    requirements: string;
} {
    return {
        id: value.id,
        region: value.region,
        created: value.created,
        country: value.country,
        estimatedTraffic: value.estimatedTraffic,
        submissionGuide: value.submissionGuide,
        name: value.name,
        description: value.description,
        updated: value.updated,
        category: to_candid_PlatformCategory_n16(_uploadFile, _downloadFile, value.category),
        estimatedSeoImpact: value.estimatedSeoImpact,
        requirements: value.requirements
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ListingStatus;
    created: Timestamp;
    userId: Principal;
    updated: Timestamp;
    notes: string;
    platformId: bigint;
    submissionDate?: Timestamp;
    submissionUrl?: string;
}): {
    status: _ListingStatus;
    created: _Timestamp;
    userId: Principal;
    updated: _Timestamp;
    notes: string;
    platformId: bigint;
    submissionDate: [] | [_Timestamp];
    submissionUrl: [] | [string];
} {
    return {
        status: to_candid_ListingStatus_n22(_uploadFile, _downloadFile, value.status),
        created: value.created,
        userId: value.userId,
        updated: value.updated,
        notes: value.notes,
        platformId: value.platformId,
        submissionDate: value.submissionDate ? candid_some(value.submissionDate) : candid_none(),
        submissionUrl: value.submissionUrl ? candid_some(value.submissionUrl) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    organization?: string;
}): {
    name: string;
    email: [] | [string];
    organization: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        organization: value.organization ? candid_some(value.organization) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: Timestamp;
    content: ContentDraft;
    versionNumber: bigint;
}): Promise<{
    created: _Timestamp;
    content: _ContentDraft;
    versionNumber: bigint;
}> {
    return {
        created: value.created,
        content: await to_candid_ContentDraft_n10(_uploadFile, _downloadFile, value.content),
        versionNumber: value.versionNumber
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlatformCategory): {
    forum: null;
} | {
    directory: null;
} | {
    news: null;
} | {
    reviewSite: null;
} | {
    contentSharing: null;
} | {
    socialMedia: null;
} {
    return value == PlatformCategory.forum ? {
        forum: null
    } : value == PlatformCategory.directory ? {
        directory: null
    } : value == PlatformCategory.news ? {
        news: null
    } : value == PlatformCategory.reviewSite ? {
        reviewSite: null
    } : value == PlatformCategory.contentSharing ? {
        contentSharing: null
    } : value == PlatformCategory.socialMedia ? {
        socialMedia: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    notStarted: null;
} | {
    submitted: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == ListingStatus.notStarted ? {
        notStarted: null
    } : value == ListingStatus.submitted ? {
        submitted: null
    } : value == ListingStatus.rejected ? {
        rejected: null
    } : value == ListingStatus.accepted ? {
        accepted: null
    } : value == ListingStatus.inProgress ? {
        inProgress: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ContentDraftVersion>): Promise<Array<_ContentDraftVersion>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ContentDraftVersion_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
